import Image from "next/image";
import Hello from "../components/hello";

export const metadata = {
  title: "Home | Next.js",
  description: "Generated by Arham!",
}

export default function Home() {
  console.log("What am I Douing here? -- Server or client?");
  return (
    <div>
      <h1 className="text-3xl">Welcome BOY!!</h1>
      <img src="./pixelpact readers logo.png" alt="" />
    </div>
  );
}
